server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: dimensionAnalysisService
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址